name = "registry-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-29"
[[kv_namespaces]]
binding = "REGISTRY_MAPS"
id = "c0021b4c86374f51852134f4fff357f1"
[dev]
ip = "127.0.0.1"
port = 8888
local_protocol = "https"
